version: '3.7'
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@55word123"
      ACCEPT_EULA: "Y"
    volumes:
      - "./data/:/var/opt/mssql/data"
      - "./log/:/var/opt/mssql/log"
      